# Generated by Django 5.2.8 on 2025-11-16 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g., Home, Work, etc.", max_length=50),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("GB", "United Kingdom"),
                            ("AU", "Australia"),
                            ("DE", "Germany"),
                            ("FR", "France"),
                            ("IT", "Italy"),
                            ("ES", "Spain"),
                            ("NL", "Netherlands"),
                            ("BE", "Belgium"),
                            ("SE", "Sweden"),
                            ("NO", "Norway"),
                            ("DK", "Denmark"),
                            ("FI", "Finland"),
                            ("IE", "Ireland"),
                            ("CH", "Switzerland"),
                            ("AT", "Austria"),
                            ("PL", "Poland"),
                            ("PT", "Portugal"),
                            ("GR", "Greece"),
                            ("JP", "Japan"),
                            ("KR", "South Korea"),
                            ("CN", "China"),
                            ("SG", "Singapore"),
                            ("HK", "Hong Kong"),
                            ("NZ", "New Zealand"),
                            ("MX", "Mexico"),
                            ("BR", "Brazil"),
                            ("AR", "Argentina"),
                            ("IN", "India"),
                        ],
                        default="US",
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
